"""The recorder served over TLS.

A phone will not open the microphone over plain HTTP: browsers withhold
getUserMedia outside a secure context, and a LAN address is not one. These
tests drive a real handshake against a real socket, because the failure this
guards against - a certificate the server loads but a client cannot complete a
handshake with - only exists on the wire.

The certificate here is generated by the test, not by mkcert: it proves the
server's TLS wiring, which is what the code owns. Whether a phone *trusts*
mkcert's CA is a property of the device, and no test on this machine can
establish it.
"""

import shutil
import ssl
import subprocess
import threading
import urllib.error
import urllib.request

import pytest

import recorder_server as srv
import whisper_pipeline as wp

LINE = "this is a deliberately long sentence with plenty of words in it number {n}."


@pytest.fixture
def certificate(tmp_path):
    """A self-signed cert/key pair named the way mkcert names them."""
    if not (openssl := shutil.which("openssl")):
        pytest.skip("openssl is not installed; cannot mint a test certificate")

    cert = tmp_path / "localhost.pem"
    key = tmp_path / "localhost-key.pem"
    subprocess.run(
        [openssl, "req", "-x509", "-newkey", "rsa:2048", "-nodes",
         "-keyout", str(key), "-out", str(cert), "-days", "1",
         "-subj", "/CN=localhost",
         "-addext", "subjectAltName=DNS:localhost,IP:127.0.0.1"],
        capture_output=True, check=True, timeout=60,
    )
    return cert


@pytest.fixture
def config(tmp_path):
    scripts = tmp_path / "scripts"
    (scripts / "es").mkdir(parents=True)
    (scripts / "es" / "a.txt").write_text(
        "\n\n".join(LINE.format(n=n) for n in range(4)), encoding="utf8"
    )
    audio = tmp_path / "data"
    audio.mkdir()
    return srv.Config(scripts, tmp_path / "dataset.csv", audio, srv.STATIC_DIR)


@pytest.fixture
def tls_server(config, certificate):
    """A live HTTPS server on an ephemeral port."""
    server = srv.build_server(config, "127.0.0.1", 0, certificate)
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"https://127.0.0.1:{server.server_address[1]}", certificate
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def get(url, cert):
    """A request that trusts exactly this certificate and no other."""
    context = ssl.create_default_context(cafile=str(cert))
    with urllib.request.urlopen(url, context=context, timeout=10) as response:
        return response.status, response.read()


class TestTheServerSpeaksTls:
    def test_a_client_trusting_the_cert_completes_the_handshake(self, tls_server):
        base, cert = tls_server
        status, _ = get(f"{base}/api/scripts", cert)
        assert status == 200

    def test_the_api_answers_the_same_over_tls(self, tls_server):
        """TLS wraps the socket; it must not change a single response body."""
        base, cert = tls_server
        _, body = get(f"{base}/api/scripts", cert)
        assert b"es/a.txt" in body

    def test_a_plain_http_request_is_refused(self, tls_server):
        """The listener is TLS-only, so http:// to the same port cannot work.

        This is the mistake a user actually makes - typing http:// at an https
        server - and it must fail as a connection error, never as a page served
        in the clear that then silently denies the microphone.
        """
        base, _ = tls_server
        plain = base.replace("https://", "http://")
        with pytest.raises((urllib.error.URLError, ConnectionError, ssl.SSLError)):
            urllib.request.urlopen(plain, timeout=10)

    def test_an_untrusting_client_rejects_the_certificate(self, tls_server):
        """The default trust store must not accept a self-signed cert."""
        base, _ = tls_server
        with pytest.raises(urllib.error.URLError):
            urllib.request.urlopen(base + "/api/scripts", timeout=10)


class TestTheCertificateIsResolved:
    def test_the_key_is_found_beside_the_certificate(self, certificate):
        """mkcert writes NAME.pem and NAME-key.pem; the pair loads from one path."""
        assert srv.tls_context(certificate) is not None

    def test_a_missing_certificate_names_the_path(self, tmp_path):
        with pytest.raises(wp.PipelineError, match="TLS file not found"):
            srv.tls_context(tmp_path / "absent.pem")

    def test_a_certificate_without_its_key_names_the_key(self, tmp_path):
        """The half-configured case: a cert copied over without its key."""
        lonely = tmp_path / "lonely.pem"
        lonely.write_text("not a real certificate", encoding="utf8")
        with pytest.raises(wp.PipelineError, match="lonely-key.pem"):
            srv.tls_context(lonely)


class TestPlainHttpIsStillTheDefault:
    def test_no_certificate_means_no_tls(self, config):
        """Nothing changes for the localhost dev loop."""
        server = srv.build_server(config, "127.0.0.1", 0)
        try:
            assert not isinstance(server.socket, ssl.SSLSocket)
        finally:
            server.server_close()


class TestASilentPeerCannotStallTheServer:
    """A TLS handshake must not run on the accept thread.

    Wrapping the listening socket puts it there, and socketserver hands a
    connection to a worker only after get_request() returns - so one peer that
    opens a connection and never sends a ClientHello blocks every other
    client. A LAN-facing box meets this without an attacker: a port scanner,
    or a phone that sleeps on Safari's certificate interstitial.
    """

    def test_a_connection_that_never_handshakes_does_not_block_others(self, tls_server):
        import socket
        base, cert = tls_server
        port = int(base.rsplit(":", 1)[1])

        silent = socket.create_connection(("127.0.0.1", port))
        try:
            status, _ = get(f"{base}/api/scripts", cert)
            assert status == 200
        finally:
            silent.close()

    def test_many_silent_peers_still_leave_the_server_answering(self, tls_server):
        import socket
        base, cert = tls_server
        port = int(base.rsplit(":", 1)[1])

        peers = [socket.create_connection(("127.0.0.1", port)) for _ in range(5)]
        try:
            assert get(f"{base}/api/scripts", cert)[0] == 200
        finally:
            for peer in peers:
                peer.close()
